#!/bin/sh
# Name: belief maching
# init-scrip

DAEMON="belief-matching.py"
BASEPATH="/usr/local/bin/belief-maching/"
PID="/var/run/belief-maching"
PORT="80"

cd $BASEPATH
#test -f $DAEMON || exit 0


case "$1" in
  start)
    echo -n "Start.... "
    nohup python $DAEMON $PORT &>> /var/log/belief-maching.log &
    echo $! > ${PID}
    echo "PID: " 
    cat ${PID}
    echo "....oky"
    echo -n "== Start server ==" >> /var/log/belief-maching.log &
    ;;
  stop)
    echo -n "Stop.... "
    kill `cat ${PID}`
    echo -n "== Stoppe server ==" >> /var/log/belief-maching.log &
    echo  > ${PID}
    echo "."
    ;;
  restart)
    echo -n "Stop.... "
    kill `cat ${PID}`
    echo "...."
    echo -n " ...Start "
    nohup python $DAEMON $PORT &>> /var/log/belief-maching.log &
    echo $! > ${PID}
    echo "PID: " 
    cat ${PID}
    echo "....oky"
    echo -n "== Start server ==" >> /var/log/belief-maching.log &
    ;;
  *)
    echo "Usage: ${0} {start|stop|restart}"
    exit 1
    ;;
esac
