#!/bin/sh
# Name: belief maching
# init-scrip

DAEMON="belief-matching.py"
BASEPATH="/usr/local/bin/belief-maching/"
PID="/var/run/belief-maching"
PORT="80"

cd $BASEPATH
#test -f $DAEMON || exit 0


case "$1" in
  start)
    echo -n "Start belief-maching"
    nohup python $DAEMON $PORT &>> /var/log/belief-maching.log &
    echo $! > ${PID}
    echo "."
    ;;
  stop)
    echo -n "Stoppe belief-maching"
    kill `cat ${PID}`
    echo  > ${PID}
    echo "."
    ;;
  restart)
    echo -n "Stoppe belief-maching"
    kill `cat ${PID}`
    echo "."
    echo -n "Start hcmt-web"
    nohup python $DAEMON $PORT &>> /var/log/belief-maching.log &
    echo  $! > ${PID}
    echo "."
    ;;
  *)
    echo "Usage: ${0} {start|stop|restart}"
    exit 1
    ;;
esac
